export const LOGIN_REQUEST = 'AUTHENTICATION/LOGIN_REQUEST'
export const LOGOUT = 'AUTHENTICATION/LOGOUT'
export const LOGIN_SUCCESS = 'AUTHENTICATION/LOGIN_SUCESS'
export const LOGIN_FAILURE = 'AUTHENTICATION/LOGIN_FAILURE'

export default {
  LOGIN_REQUEST,
  LOGOUT,
  LOGIN_SUCCESS,
  LOGIN_FAILURE
}
