export const LOGIN_REQUEST = 'AUTHENTICATION/LOGIN_REQUEST'
export const LOGOUT = 'AUTHENTICATION/LOGOUT'
export const LOGIN_SUCCESS = 'AUTHENTICATION/LOGIN_SUCESS'
export const LOGIN_FAILURE = 'AUTHENTICATION/LOGIN_FAILURE'
export const LOGIN_CHECK = 'AUTHENTICATION/LOGIN_CHECK'
export const REFRESH_CAPTCHA = 'AUTHENTICATION/REFRESH_CAPTCHA'
export const LOAD_CAPTCHA = 'AUTHENTICATION/LOAD_CAPTCHA'
export const LOADED_CAPTCHA = 'AUTHENTICATION/LOADED_CAPTCHA'
export const INIT_APP = 'AUTHENTICATION/INIT_APP'

export default {
  LOGIN_REQUEST,
  LOGOUT,
  LOGIN_SUCCESS,
  LOGIN_FAILURE,
  LOGIN_CHECK,
  REFRESH_CAPTCHA,
  LOAD_CAPTCHA,
  INIT_APP,
  LOADED_CAPTCHA
}
