export const EMPLEADOS_REQUEST = 'EMPLEADOS/EMPLEADOS_REQUEST'
export const EMPLEADOS_SUCCESS = 'EMPLEADOS/EMPLEADOS_SUCCESS'
export const EMPLEADOS_FAILED = 'EMPLEADOS/EMPLEADOS_FAILED'

export const EDIT_EMPLEADO_REQUEST = 'EMPLEADOS/EDIT_EMPLEADO_REQUEST'
export const EDIT_EMPLEADO_SUCCESS = 'EMPLEADOS/EDIT_EMPLEADO_SUCESS'
export const EDIT_EMPLEADO_FAILED = 'EMPLEADOS/EDIT_EMPLEADO_FAILED'

export const INVITE_EMPLEADO_REQUEST = 'EMPLEADOS/INVITE_EMPLEADO_REQUEST'
export const INVITE_EMPLEADO_SUCCESS = 'EMPLEADOS/INVITE_EMPLEADO_SUCCESS'
export const INVITE_EMPLEADO_FAILED = 'EMPLEADOS/INVITE_EMPLEADO_FAILED'

export default {
  EMPLEADOS_REQUEST,
  EMPLEADOS_SUCCESS,
  EMPLEADOS_FAILED,
  EDIT_EMPLEADO_REQUEST,
  EDIT_EMPLEADO_FAILED,
  EDIT_EMPLEADO_SUCCESS,
  INVITE_EMPLEADO_REQUEST,
  INVITE_EMPLEADO_SUCCESS,
  INVITE_EMPLEADO_FAILED
}
